### ISSUE TITLE
Not seeing battery service with charge level...

### ISSUE THREAD

**Issue by winterhalder** [joeshaw/carwings-homecontrol#3] opened 2019-02-17 17:03 UTC
Also tells me climate control is on, when it is off.

Also getting this error:

INFO 2019/02/17 11:53:16 Non-admin controllers are not allowed to add pairings

Known issues? Is it still working for you?

**Comment by joeshaw** [comment] 2019-02-19 14:59
That error message is caused by a bug in the [homecontrol library](https://github.com/brutella/hc) that the program uses.  I'd suggest updating that (`go get -u github.com/brutella/hc`) and then rebuilding carwings-homecontrol (`go install github.com/joeshaw/carwings-homecontrol/...`).

However, I don't know if that will solve the issue of it mis-reporting the climate status.  Let me know if it fixes things.

**Comment by winterhalder** [comment] 2019-02-19 15:04
Thanks Joe.

BTW - I *was* able to get things working - I found the battery status in the details of the homekit devices (and siri will answer my question as to batter level - so that's great) - and I made a couple more mods to my version of your carwings library to basically assume climate is "OFF" if it doesn't get a valid response (instead of assuming ON). 

Anyway, working pretty well now!  Thanks a bunch!

**Comment by joeshaw** [comment] 2019-02-19 15:16
Oops, I misread the commit history of that error.  You'd have to jump back to `805e4aef40191d35dabd229e903fabedb4eea316^` which is the commit that introduced it.  The author has a fix on a branch but it hasn't been merged yet.  But, it seems like it's not related to the issue you were seeing.

I'll close this out but if you see other issues please file 'em!

**Closed as completed by joeshaw** 2019-02-19 15:16 UTC
